/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package folder1;

import static folder1.Restoran.bekleyenMusteriListesi;
import static folder1.Restoran.garsonListesi;
import static folder1.Restoran.musteriListesi;
import static folder1.Restoran.sefListesi;
import static folder1.Restoran.texteYazilacaklar;
import static folder1.Restoran.oturanMusteriListesi;
import java.awt.Color;
import java.awt.TextArea;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JList;

/**
 *
 * @author Orhan UZEL
 */
public class GarsonEkrani extends javax.swing.JFrame {
    
    
MusteriEkrani musteriEkrani;
Restoran restoran;
public AsciEkrani asciEkrani=new AsciEkrani(this,restoran);
 // AsciEkrani asciEkrani=new AsciEkrani(this,restoran);

 public static   TextArea textSiparisler;
 public static  List<String> texteYazilacaklar ;
    /**
     * Creates new form GarsonEkrani
     */
    public GarsonEkrani(MusteriEkrani musteriEkrani,Restoran restoran) {
        asciEkrani.restoran=restoran;
       // textPaneSiparisAlma.setText(textSiparisler.getText());//bakacağzzz
        this.restoran=restoran;
        this.musteriEkrani=musteriEkrani;
       
        initComponents();
       
          this.setLocationRelativeTo(null);//açılan ekranı merkezde konumlandııyor
          setLocation(700, 0);
          this.setSize(600,500);
    }
    
//    public void garsonCalistir(JList list1){
//         // 3 garson oluştur
//        for (int i = 1; i <= 3; i++) {
//            garsonListesi.add(new Garson(i, musteriListesi, bekleyenMusteriListesi, sefListesi,texteYazilacaklar,list1));
//          //  textSiparisler.setText((Garson.textSiparisler.getText()));
//            
//        }
//        
//        
//        for (Garson garson : garsonListesi) {
//            
//            garson.start();
//        }
//        //return textSiparisler;
//    }
//    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnGarson3 = new javax.swing.JButton();
        btnGarson2 = new javax.swing.JButton();
        btnGarson1 = new javax.swing.JButton();
        list1 = new java.awt.List();
        button1 = new java.awt.Button();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGarson3.setBackground(new java.awt.Color(204, 255, 255));
        btnGarson3.setText("Garson3");
        jPanel1.add(btnGarson3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, -1, -1));

        btnGarson2.setBackground(new java.awt.Color(204, 255, 255));
        btnGarson2.setText("Garson2");
        jPanel1.add(btnGarson2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, -1, -1));

        btnGarson1.setBackground(new java.awt.Color(204, 255, 255));
        btnGarson1.setText("Garson1");
        btnGarson1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnGarson1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, -1, -1));

        list1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.add(list1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 382, 280));

        button1.setBackground(new java.awt.Color(204, 255, 255));
        button1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button1.setLabel("Siparişleri Al");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel1.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 101, 96, 58));

        jButton2.setBackground(new java.awt.Color(204, 255, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButton2.setText("Önceki Sayfaya Dön");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 101, 57));

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setText("Aşçıya Geç");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 99, 57));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    musteriEkrani.setVisible(true);
   // this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
    //  texteYazilacaklar =(List<String>) restoran.garsonCalistir((TextArea) texteYazilacaklar);
       garsonCalistir(list1);
       
//       for(int i=0;i<Restoran.texteYazilacaklar.size();i++){
//           System.out.println("+++++++++++++++++++++++++++++++++++++++++++++:->  "+Restoran.texteYazilacaklar.get(i)+"  ++++++++++++++++++++++++++++++++++++++++++++++++++++");
//          // list1.add(Garson.texteYazilacaklar.get(i));//bakacağzzz
//           list1.add(Restoran.texteYazilacaklar.get(i), i);
//       }
       
    }//GEN-LAST:event_button1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
             asciEkrani.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
      public static void main(String args[]) {
          MusteriEkrani musteriEkrani = new MusteriEkrani();
          Restoran restoran=new Restoran();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GarsonEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GarsonEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GarsonEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GarsonEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GarsonEkrani(musteriEkrani,restoran).setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGarson1;
    private javax.swing.JButton btnGarson2;
    private javax.swing.JButton btnGarson3;
    private java.awt.Button button1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private java.awt.List list1;
    // End of variables declaration//GEN-END:variables

        
    private void garsonCalistir(java.awt.List list1) {
  
        // 3 garson oluştur
        for (int i = 1; i <= 3; i++) {
            garsonListesi.add(new Garson(i, musteriListesi, bekleyenMusteriListesi, sefListesi,list1,oturanMusteriListesi));
          //  textSiparisler.setText((Garson.textSiparisler.getText()));
            
        }
       // ButtonGroup btnGroup=new ButtonGroup();
        
        int i=1;
        for (Garson garson : garsonListesi) {
            switch (i) {
                case 1:
                    btnGarson1.setBackground(Color.PINK);
                    break;
                     case 2:
                    btnGarson2.setBackground(Color.PINK);
                    break;
                     case 3:
                    btnGarson3.setBackground(Color.PINK);
                    break;
                    
                default:
                    throw new AssertionError();
            }
            garson.start();
           
            i++;        
        }
        //return textSiparisler;
        
    }
}
