/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package folder1;

import java.awt.Color;
import static java.lang.System.exit;

/**
 *
 * @author Orhan UZEL
 */
public class KasaEkrani extends javax.swing.JFrame {
AsciEkrani asciEkrani;
Restoran restoran;
    /**
     * Creates new form KasaEkrani
     */
    public KasaEkrani(AsciEkrani asciEkrani, Restoran restoran) {
        this.asciEkrani=asciEkrani;
        this.restoran=restoran;
        initComponents();
        setLocation(700,310);
        this.setSize(600,420);
       // this.setLocationRelativeTo(null);
    }
    public void kasiyerBaslat(){
     Kasiyer kasiyer = new Kasiyer(list1);
        kasiyer.start();
          btnKasiyer.setBackground(Color.orange);
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnKasiyer = new javax.swing.JButton();
        list1 = new java.awt.List();
        label1 = new java.awt.Label();
        btnKasaBaslat = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnKasiyer.setBackground(new java.awt.Color(204, 255, 204));
        btnKasiyer.setText("Kasiyer");
        jPanel1.add(btnKasiyer, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, -1));

        list1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.add(list1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 285, 270));

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        label1.setText("KASA İŞLEMLERİ");
        jPanel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 97, 280, -1));

        btnKasaBaslat.setBackground(new java.awt.Color(204, 255, 204));
        btnKasaBaslat.setText("KASA İŞLEMLERİNİ BAŞLAT");
        btnKasaBaslat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKasaBaslat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKasaBaslatActionPerformed(evt);
            }
        });
        jPanel1.add(btnKasaBaslat, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        jButton3.setBackground(new java.awt.Color(204, 255, 204));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jButton3.setText("Aşçı İşlemlerine Dön");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, 24));

        jButton4.setBackground(new java.awt.Color(204, 255, 204));
        jButton4.setText("Programı Bitir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, 24));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 760, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKasaBaslatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKasaBaslatActionPerformed
        kasiyerBaslat();
       
    }//GEN-LAST:event_btnKasaBaslatActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        AsciEkrani asciEkrani = null;
        Restoran restoran = null;
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KasaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KasaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KasaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KasaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KasaEkrani(asciEkrani, restoran).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKasaBaslat;
    private javax.swing.JButton btnKasiyer;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private java.awt.List list1;
    // End of variables declaration//GEN-END:variables
}
